### ISSUE TITLE
damaged sparkle feed

### ISSUE THREAD

**Issue by core-code** [onmyway133/archives#1]
this commit is damaged

https://github.com/onmyway133/archives/commit/4215288751ccdaf13e1e9c204f772c7a0bc6d244

you forgot the `<description>` tag around the `CDATA`

**Comment by onmyway133** [comment]
@core-code thanks for letting me know ❤️

**Comment by core-code** [comment]
no problem, thanks for resolving it.

there seems to be another issue - the linked file

https://raw.githubusercontent.com/onmyway133/archives/master/Almighty.zip

does not seem to exist

**Comment by onmyway133** [comment]
@core-code thanks, I've updated it to https://almighty-app.s3.eu-north-1.amazonaws.com/Almighty.zip
Do you use Almighty app @core-code ?

**Comment by core-code** [comment]
thanks!

no, we noticed the issues because the malformed sparkle feed crashed our #MacUpdater app ;-)
