### ISSUE TITLE
The download link in /archives/master/PastePal.xml is wrong

### ISSUE THREAD

**Issue by cdwmhcc** [onmyway133/archives#3]
https://raw.githubusercontent.com/onmyway133/archives/master/PastePal.xml

<enclosure url="https://almighty-app.s3.eu-north-1.amazonaws.com/PastePal.zi" length="15048405" type="application/octet-stream"/> The suffix of the url should be `.zip` instead of `.zi`

**Comment by onmyway133** [comment]
@cdwmhcc Hi thanks for letting me know, I've fixed that 👍
